Repository Ayushparikh-code/Web-dev-mini-projects, pull requests merged in 2021-07, with the labels that each got.

#12 to do list separate file
  To-Do List/.gitkeep
  To-Do List/HTML
  To-Do List/css
  To-Do List/javascript
Labels: LGMSOC21

#15 Added Random Color Generator
  Random Color Generator/randomcolor.css
  Random Color Generator/randomcolor.html
  Random Color Generator/randomcolor.js
Labels: LGMSOC21

#18 Added JavaScript Drum Kit
  .vscode/settings.json
  Javascript DrumKit/images/crash.png
  Javascript DrumKit/images/kick.png
  Javascript DrumKit/images/snare.png
  Javascript DrumKit/images/tom1.png
  Javascript DrumKit/images/tom2.png
  Javascript DrumKit/images/tom3.png
  Javascript DrumKit/images/tom4.png
  Javascript DrumKit/index.html
  Javascript DrumKit/script.js
  Javascript DrumKit/sounds/crash.mp3
  Javascript DrumKit/sounds/kick-bass.mp3
  Javascript DrumKit/sounds/snare.mp3
  Javascript DrumKit/sounds/tom-1.mp3
  Javascript DrumKit/sounds/tom-2.mp3
  Javascript DrumKit/sounds/tom-3.mp3
  Javascript DrumKit/sounds/tom-4.mp3
  Javascript DrumKit/style.css
Labels: LGMSOC21

#23 Calculator app added
  CALCULATOR/index.html
  CALCULATOR/index.js
  CALCULATOR/style.css
Labels: LGMSOC21

#22 Added TicTacToe
  Tic-Tac-Toe Game/index.html
  Tic-Tac-Toe Game/script.js
  Tic-Tac-Toe Game/style.css
Labels: LGMSOC21

#21 BUILD A QUIZ APP #7
  QUIZ WEB APP/end.html
  QUIZ WEB APP/end.js
  QUIZ WEB APP/game.css
  QUIZ WEB APP/game.html
  QUIZ WEB APP/game.js
  QUIZ WEB APP/highscores.css
  QUIZ WEB APP/highscores.html
  QUIZ WEB APP/highscores.js
  QUIZ WEB APP/hogwarts.css
  QUIZ WEB APP/index.html
Labels: LGMSOC21

#29 Added Contributors List
  README.md
Labels: LGMSOC21, documentation

#30 Added Cat Generator Project🐈
  CAT GENERATOR APP/index.html
  CAT GENERATOR APP/script.js
  CAT GENERATOR APP/style.css
  JAVASCRIPT GAME/.gitkeep
  Javascript DrumKit/.gitkeep
Labels: LGMSOC21

#33 Countdown_Timer
  Countdown_Timer/deepavali.jpg
  Countdown_Timer/index.html
  Countdown_Timer/script.js
  Countdown_Timer/style.css
Labels: LGMSOC21

#36 Added Weather App
  Weather-App/README.md
  Weather-App/Weather-App.jpg
  Weather-App/index.html
  Weather-App/sample.mp4
  Weather-App/script.js
  Weather-App/style.css
Labels: LGMSOC21

#47 Love calculator app
  DIGITAL-JAVASCRIPT-CLOCK/README.md
  DIGITAL-JAVASCRIPT-CLOCK/index.html
  DIGITAL-JAVASCRIPT-CLOCK/script.js
  DIGITAL-JAVASCRIPT-CLOCK/style.css
  LOVE-CALCULATOR/README.md
  LOVE-CALCULATOR/heart.png
  LOVE-CALCULATOR/index.html
  LOVE-CALCULATOR/script.js
  LOVE-CALCULATOR/style.css
Labels: LGMSOC21

#54 Added Custom-Range-Slider
  Custom-Range-Slider/Custom-Range-Slider.png
  Custom-Range-Slider/README.md
  Custom-Range-Slider/index.html
  Custom-Range-Slider/script.js
  Custom-Range-Slider/style.css
Labels: LGMSOC21

#72 Added Clock-Stopwatch Project
  Clock-Stopwatch/README.md
  Clock-Stopwatch/assests/scripts.js
  Clock-Stopwatch/assests/stopwatch-2.JPG
  Clock-Stopwatch/assests/stopwatch.JPG
  Clock-Stopwatch/assests/stopwatch3.JPG
  Clock-Stopwatch/assests/styles.css
  Clock-Stopwatch/index.html
Labels: LGMSOC21

#70 added news-web-app
  flask_news_project/app.py
  flask_news_project/readme.md
  flask_news_project/requirements.txt
  flask_news_project/templates/business.html
  flask_news_project/templates/crypto.html
  flask_news_project/templates/ent.html
  flask_news_project/templates/headlines.html
  flask_news_project/templates/home.html
  flask_news_project/templates/images/a.png
  flask_news_project/templates/images/b.png
  flask_news_project/templates/images/c.png
  flask_news_project/templates/layout.html
  flask_news_project/templates/science.html
  flask_news_project/templates/sports.html
  flask_news_project/templates/tech.html
Labels: LGMSOC21

#34 Jump Game
  JAVASCRIPT GAME/Jump Game/Readme.md
  JAVASCRIPT GAME/Jump Game/index.html
  JAVASCRIPT GAME/Jump Game/script.js
  JAVASCRIPT GAME/Jump Game/style.css
Labels: LGMSOC21

#100 joke-app-added
  React-joke-app/.gitignore
  React-joke-app/README.md
  React-joke-app/package-lock.json
  React-joke-app/package.json
  React-joke-app/public/favicon.ico
  React-joke-app/public/index.html
  React-joke-app/public/manifest.json
  React-joke-app/public/robots.txt
  React-joke-app/src/App.css
  React-joke-app/src/App.js
  React-joke-app/src/components/Footer.js
  React-joke-app/src/components/Home.js
  React-joke-app/src/components/Joke.js
  React-joke-app/src/index.css
  React-joke-app/src/index.js
  React-joke-app/src/reportWebVitals.js
  React-joke-app/src/setupTests.js
Labels: Level4, approved

#103 #90 expense tracker
  Expense Tracker/.gitignore
  Expense Tracker/README.md
  Expense Tracker/package-lock.json
  Expense Tracker/package.json
  Expense Tracker/public/favicon.ico
  Expense Tracker/public/index.html
  Expense Tracker/public/logo192.png
  Expense Tracker/public/logo512.png
  Expense Tracker/public/manifest.json
  Expense Tracker/public/robots.txt
  Expense Tracker/src/App.js
  Expense Tracker/src/assets/money.jpg
  Expense Tracker/src/components/Details/Details.jsx
  Expense Tracker/src/components/Details/styles.js
  Expense Tracker/src/components/InfoCard.jsx
  Expense Tracker/src/components/Main/Form/Form.jsx
  Expense Tracker/src/components/Main/Form/styles.js
  Expense Tracker/src/components/Main/List/List.jsx
  Expense Tracker/src/components/Main/List/styles.js
  Expense Tracker/src/components/Main/Main.jsx
  Expense Tracker/src/components/Main/styles.js
  Expense Tracker/src/components/Snackbar/Snackbar.jsx
  Expense Tracker/src/components/Snackbar/styles.js
  Expense Tracker/src/components/index.js
  Expense Tracker/src/constants/categories.js
  Expense Tracker/src/context/context.js
  Expense Tracker/src/context/contextReducer.js
  Expense Tracker/src/index.css
  Expense Tracker/src/index.js
  Expense Tracker/src/styles.js
  Expense Tracker/src/useTransactions.js
  Expense Tracker/src/utils/formatDate.js
Labels: LGMSOC21, Level4, approved

#102 Chuck Norris jokes
  Chuck-Norris-Jokes/ChuckNorris.png
  Chuck-Norris-Jokes/Readme.md
  Chuck-Norris-Jokes/index.html
  Chuck-Norris-Jokes/index.js
  Chuck-Norris-Jokes/style.css
Labels: LGMSOC21

#109 Added Rock paper scissor Game
  Rock-Paper-Scissor Game/README.md
  Rock-Paper-Scissor Game/images/paper.jpeg
  Rock-Paper-Scissor Game/images/rock.jpeg
  Rock-Paper-Scissor Game/images/scissors.jpeg
  Rock-Paper-Scissor Game/index.html
  Rock-Paper-Scissor Game/script.js
  Rock-Paper-Scissor Game/style.css
Labels: LGMSOC21

#118 Added Age calculator!!
  age-calculator/README.md
  age-calculator/index.html
  age-calculator/script.js
  age-calculator/style.css
Labels: LGMSOC21, Level4

#120 Add Form validation in js.
  form-validation/README.md
  form-validation/index.html
  form-validation/script.js
  form-validation/style.css
Labels: LGMSOC21, Level4

#127 Gym website
  MyGym Website/README.md
  MyGym Website/css/aos.css
  MyGym Website/css/bootstrap.min.css
  MyGym Website/css/font-awesome.min.css
  MyGym Website/css/main.css
  MyGym Website/fonts/FontAwesome.otf
  MyGym Website/fonts/Plain-Bold.woff
  MyGym Website/fonts/Plain-Bold.woff2
  MyGym Website/fonts/Plain-Light.woff
  MyGym Website/fonts/Plain-Light.woff2
  MyGym Website/fonts/Plain-Regular.woff
  MyGym Website/fonts/Plain-Regular.woff2
  MyGym Website/fonts/fontawesome-webfont.eot
  MyGym Website/fonts/fontawesome-webfont.svg
  MyGym Website/fonts/fontawesome-webfont.ttf
  MyGym Website/fonts/fontawesome-webfont.woff
  MyGym Website/fonts/fontawesome-webfont.woff2
  MyGym Website/images/class/cardio-class.jpg
  MyGym Website/images/class/crossfit-class.jpg
  MyGym Website/images/class/yoga-class.jpg
  MyGym Website/images/hero-bg.jpg
  MyGym Website/images/output/output1.png
  MyGym Website/images/output/output2.png
  MyGym Website/images/output/output3.png
  MyGym Website/images/team/undraw_energizer_2224.svg
  MyGym Website/images/team/undraw_yoga_248n.svg
  MyGym Website/index.html
  MyGym Website/js/aos.js
  MyGym Website/js/bootstrap.min.js
  MyGym Website/js/custom.js
  MyGym Website/js/jquery.min.js
  MyGym Website/js/smoothscroll.js
Labels: LGMSOC21, Level4

#129 Add Text Analyzer
  Text Analyzer/README.md
  Text Analyzer/SS1.png
  Text Analyzer/SS2.png
  Text Analyzer/index.html
  Text Analyzer/script.js
  Text Analyzer/style.css
Labels: LGMSOC21, Level4

#132 Issue No. #8 Re-solved Updated the Readme of Basic Portfolio Website with Screenshots
  Basic Portfolio Website/.gitkeep
  Basic Portfolio Website/Readme.md
  Basic Portfolio Website/favicon.ico
  Basic Portfolio Website/images/0_7rudMaePHd-1TXRx.jpg
  Basic Portfolio Website/images/Group 1949.svg
  Basic Portfolio Website/images/Group 1951.svg
  Basic Portfolio Website/images/Group 1953.svg
  Basic Portfolio Website/images/Group 1956.svg
  Basic Portfolio Website/images/Path 5023.png
  Basic Portfolio Website/images/Rectangle 565.svg
  Basic Portfolio Website/images/Rectangle 5651.svg
  Basic Portfolio Website/images/behance.png
  Basic Portfolio Website/images/blackball.svg
  Basic Portfolio Website/images/portitem1.png
  Basic Portfolio Website/images/portitem2.png
  Basic Portfolio Website/images/portitem3.png
  Basic Portfolio Website/images/profileimg.jpg
  Basic Portfolio Website/images/sitebg.jpg
  Basic Portfolio Website/images/sitebg2.jpg
  Basic Portfolio Website/index.html
  Basic Portfolio Website/main.css
  Basic Portfolio Website/main.js
  Basic Portfolio Website/screenshots/Screenshot (1003).png
  Basic Portfolio Website/screenshots/Screenshot (1004).png
  Basic Portfolio Website/screenshots/Screenshot (1005).png
  Basic Portfolio Website/screenshots/Screenshot (1006).png
  Basic Portfolio Website/screenshots/Screenshot (1007).png
  Basic Portfolio Website/screenshots/Screenshot (1008).png
  Basic Portfolio Website/screenshots/Screenshot (1009).png
  Basic Portfolio Website/screenshots/Screenshot (1010).png
  Basic Portfolio Website/screenshots/Screenshot (1011).png
Labels: LGMSOC21

#123 Created index.md
  Index.md
Labels: LGMSOC21, under-review

#116 Ping pong Ball Score Keeper
  Index.md
  Score-Keeper/Readme.md
  Score-Keeper/Score_keeper.css
  Score-Keeper/Score_keeper.html
  Score-Keeper/Score_keeper.js
Labels: LGMSOC21, Level4

#82 dice game created and added.
  DiceGame/Readme.md
  DiceGame/images/DiceGame2.png
  DiceGame/images/DiceGame3.png
  DiceGame/images/dice1.png
  DiceGame/images/dice2.png
  DiceGame/images/dice3.png
  DiceGame/images/dice4.png
  DiceGame/images/dice5.png
  DiceGame/images/dice6.png
  DiceGame/images/diceGame1.png
  DiceGame/index.html
  DiceGame/script.js
  DiceGame/styles.css
Labels: LGMSOC21

#141 Index.md
  Index.md
Labels: LGMSOC21, Level1

#142 Added classroom website in the repository
  CLASSROOM SCHEDULER WEBSITE/README.md
  CLASSROOM SCHEDULER WEBSITE/classroom.png
  CLASSROOM SCHEDULER WEBSITE/index.html
  CLASSROOM SCHEDULER WEBSITE/script.js
  CLASSROOM SCHEDULER WEBSITE/style.css
Labels: LGMSOC21, Level4

#136 FAQ Application
  FAQ Application/README.md
  FAQ Application/ScreenShots/ss1.png
  FAQ Application/ScreenShots/ss2.png
  FAQ Application/index.html
  FAQ Application/script.js
  FAQ Application/style.css
Labels: LGMSOC21

#155 Image-Filter-App
  Image-Filter-App/Image-Filter-App.png
  Image-Filter-App/README.md
  Image-Filter-App/index.html
  Image-Filter-App/script.js
  Image-Filter-App/style.css
  Index.md
Labels: LGMSOC21

#158 Added details of age-calculator and form-validation in index.md
  Index.md
Labels: LGMSOC21, Level0, approved

#162 ADDED BMI CALCULATOR
  Index.md
  bmi-calculator/README.md
  bmi-calculator/index.html
  bmi-calculator/script.js
  bmi-calculator/style.css
Labels: LGMSOC21, Level4

#164 Added Glassmorphism Animation Form
  Glassmorphism-Form/README.md
  Glassmorphism-Form/index.html
  Glassmorphism-Form/style.css
  Index.md
Labels: LGMSOC21, Level4

#173 Battery Percentage Indicator
  Battery Indicator/README.md
  Battery Indicator/dark.jpg
  Battery Indicator/index.html
  Battery Indicator/light.jpg
  Battery Indicator/script.js
  Battery Indicator/style.css
  Index.md
Labels: LGMSOC21, Level4

#133 ConnectFour
  ConnectFour/Part3_FrontEndProject.css
  ConnectFour/Part3_FrontEndProject.html
  ConnectFour/Part3_FrontEndProject.js
  ConnectFour/README.md
  Index.md
Labels: LGMSOC21, Level4, approved

#180 Update Index.md
  Index.md
Labels: LGMSOC21, Level0

#181 Added expand button
  Expand-Button/README.md
  Expand-Button/index.html
  Expand-Button/script.js
  Expand-Button/style.css
  Index.md
Labels: LGMSOC21

#179 Updated random color generator
  Random Color Generator/README.md
  Random Color Generator/Readme.md
  Random Color Generator/randomcolor.css
  Random Color Generator/randomcolor.html
  Random Color Generator/randomcolor.js
Labels: LGMSOC21

#182 added color guessing game.
  Index.md
  color-guessor/README.md
  color-guessor/index.html
  color-guessor/script.js
  color-guessor/style.css
Labels: LGMSOC21

#159 Double Vertical Slider
  Double Vertical Slider/Double-Vertical-Slider.png
  Double Vertical Slider/README.md
  Double Vertical Slider/index.html
  Double Vertical Slider/script.js
  Double Vertical Slider/style.css
  Index.md
Labels: LGMSOC21, Level4

#189 185 basic contact form
  Basic Contact Form/README.md
  Basic Contact Form/app.js
  Basic Contact Form/index.html
  Basic Contact Form/style.css
  Index.md
Labels: LGMSOC21, Level4

#183 165 day of week app
  Index.md
  Week Day Predictor App/README.md
  Week Day Predictor App/app.js
  Week Day Predictor App/index.html
  Week Day Predictor App/style.css
Labels: LGMSOC21, Level4

#172 Added Project : Compound Interest Calculator
  Compound Interest Calculator/README.md
  Compound Interest Calculator/index.html
  Compound Interest Calculator/script.js
  Compound Interest Calculator/style.css
  Index.md
Labels: LGMSOC21

#197 Update Index.md
  Index.md
Labels: LGMSOC21, Level1

#193 Youtube UI Clone
  Index.md
  Youtube-Clone/README.md
  Youtube-Clone/Resources/favicon_32x32.png
  Youtube-Clone/Resources/youtube_logo.png
  Youtube-Clone/Resources/youtube_logo.webp
  Youtube-Clone/css/styles.css
  Youtube-Clone/index.html
Labels: LGMSOC21, Level4

#168 Button change effect app
  Index.md
  JAVASCRIPT BUTTON APP/.gitignore
  JAVASCRIPT BUTTON APP/README.md
  JAVASCRIPT BUTTON APP/app.js
  JAVASCRIPT BUTTON APP/index.html
  JAVASCRIPT BUTTON APP/package-lock.json
  JAVASCRIPT BUTTON APP/package.json
  JAVASCRIPT BUTTON APP/public/css/style.css
  JAVASCRIPT BUTTON APP/public/images/challenge1.png
  JAVASCRIPT BUTTON APP/public/images/challenge2.png
  JAVASCRIPT BUTTON APP/public/js/script.js
Labels: LGMSOC21

#161 Added JS tip calc
  Index.md
  Tip Calculator/index.html
  Tip Calculator/readme.md
  Tip Calculator/script.js
  Tip Calculator/styles.css
Labels: LGMSOC21, Level4

#169 Tribute page
  Index.md
  JAVASCRIPT BUTTON APP/README.md
  TRIBUTE PAGE/.gitignore
  TRIBUTE PAGE/README.md
  TRIBUTE PAGE/app.js
  TRIBUTE PAGE/index.html
  TRIBUTE PAGE/package-lock.json
  TRIBUTE PAGE/package.json
  TRIBUTE PAGE/public/css/style.css
  TRIBUTE PAGE/public/images/tribute.png
  TRIBUTE PAGE/public/images/tribute1.png
Labels: LGMSOC21, Level4

#201 BMI calculator using Flask
  BMI Calculator (Flask)/README.md
  BMI Calculator (Flask)/app.py
  BMI Calculator (Flask)/static/style.css
  BMI Calculator (Flask)/templates/index.html
  Index.md
Labels: LGMSOC21

#205 Basic Contact Form
  Basic Contact Form/README.md
  Basic Contact Form/app.js
  Basic Contact Form/index.html
  Basic Contact Form/style.css
  Index.md
Labels: LGMSOC21, 🟥 Level4

#167 Added online quiz portal #122
  Index.md
  online quiz portal/README.md
  online quiz portal/index.html
  online quiz portal/question.js
  online quiz portal/screenshot/s1.png
  online quiz portal/script.js
  online quiz portal/style.css
Labels: LGMSOC21

#204 Added virtual keyboard
  Index.md
  Virtual Keyboard/index.html
  Virtual Keyboard/readme.md
  Virtual Keyboard/script.js
  Virtual Keyboard/style.css
Labels: LGMSOC21, 🟥 Level4

#207 Update README.md
  GOOGLE.COM PAGE PROJECT/README.md
Labels: LGMSOC21, 🟪 Level0

#210 Tindog
  Index.md
  Tindog/images/TechCrunch.png
  Tindog/images/bizinsider.png
  Tindog/images/dog-img.jpg
  Tindog/images/iphone6.png
  Tindog/images/lady-img.jpg
  Tindog/images/mashable.png
  Tindog/images/tnw.png
  Tindog/index.html
  Tindog/readme.md
  Tindog/style.css
Labels: LGMSOC21, 🟥 Level4

#199 Word counter #135
  Index.md
  word counter/Capture.JPG
  word counter/readme.md
  word counter/word.css
  word counter/word.html
  word counter/word.js
Labels: LGMSOC21, approved, 🟥 Level4

#211 Chess Game
  Chess-Game/Readme.md
  Chess-Game/index.html
  Chess-Game/script.js
  Chess-Game/style.css
  Index.md
Labels: LGMSOC21, 🟥 Level4

#218 Parallex website added
  Index.md
  parallex-website/.gitignore
  parallex-website/README.md
  parallex-website/app.js
  parallex-website/index.html
  parallex-website/package-lock.json
  parallex-website/package.json
  parallex-website/public/css/style.css
  parallex-website/public/images/demo.png
  parallex-website/public/images/pImg1.jpeg
  parallex-website/public/images/pImg2.jpeg
  parallex-website/public/images/pImg3.jpeg
Labels: LGMSOC21, 🟥 Level4

#194 Create Covid 19 Awarness Website
  Covid 19 Awarness Website/Readme.md
  Covid 19 Awarness Website/api.html
  Covid 19 Awarness Website/awarness1.png
  Covid 19 Awarness Website/awarness2.png
  Covid 19 Awarness Website/awarness3.png
  Covid 19 Awarness Website/background.png
  Covid 19 Awarness Website/hands.png
  Covid 19 Awarness Website/index.html
  Covid 19 Awarness Website/index.js
  Covid 19 Awarness Website/mask.png
  Covid 19 Awarness Website/outbreak.png
  Covid 19 Awarness Website/precuations.png
  Covid 19 Awarness Website/precuations1.png
  Covid 19 Awarness Website/protect.html
  Covid 19 Awarness Website/style.css
  Covid 19 Awarness Website/symtoms.png
  Covid 19 Awarness Website/understand1.png
  Covid 19 Awarness Website/vaccination.png
  README.md
Labels: LGMSOC21, under-review, 🟥 Level4

#219 Added Image finder
  Index.md
  image-finder-app/.gitignore
  image-finder-app/README.md
  image-finder-app/Screenshots/ss1.png
  image-finder-app/Screenshots/ss2.png
  image-finder-app/Screenshots/ss3.png
  image-finder-app/package-lock.json
  image-finder-app/package.json
  image-finder-app/public/favicon.ico
  image-finder-app/public/index.html
  image-finder-app/public/logo192.png
  image-finder-app/public/logo512.png
  image-finder-app/public/manifest.json
  image-finder-app/public/robots.txt
  image-finder-app/src/App.css
  image-finder-app/src/App.js
  image-finder-app/src/Components/BreadCrumb.js
  image-finder-app/src/Components/DisplayImages.js
  image-finder-app/src/Components/Image.js
  image-finder-app/src/Components/Navbar.js
  image-finder-app/src/Components/SnackBar.js
  image-finder-app/src/Services/api.js
  image-finder-app/src/index.css
  image-finder-app/src/index.js
Labels: LGMSOC21, 🟥 Level4

#149 added weight converter
  Index.md
  Weight Converter/README.md
  Weight Converter/index.html
  Weight Converter/main.css
  Weight Converter/screenshots/smooth_functioning.png
  Weight Converter/screenshots/when_no_value_passed.png
Labels: LGMSOC21, under-review

#220 added new project corona tracker
  Corona-tracker/.gitignore
  Corona-tracker/README.md
  Corona-tracker/package-lock.json
  Corona-tracker/package.json
  Corona-tracker/src/app.js
  Corona-tracker/views/404error.hbs
  Corona-tracker/views/about.hbs
  Corona-tracker/views/contact.hbs
  Corona-tracker/views/css/style.css
  Corona-tracker/views/hospitals.hbs
  Corona-tracker/views/images/404.gif
  Corona-tracker/views/images/404.png
  Corona-tracker/views/images/Screenshot (133).png
  Corona-tracker/views/images/Screenshot (134).png
  Corona-tracker/views/images/bed1.jpg
  Corona-tracker/views/images/corona-gif.gif
  Corona-tracker/views/images/corona.gif
  Corona-tracker/views/images/doctor.png
  Corona-tracker/views/images/hosp.png
  Corona-tracker/views/images/images (1).png
  Corona-tracker/views/images/logo.png
  Corona-tracker/views/images/nurse.jpg
  Corona-tracker/views/images/nurse1.png
  Corona-tracker/views/images/nurse2.jpg
  Corona-tracker/views/images/test1.jpg
  Corona-tracker/views/images/test2.png
  Corona-tracker/views/images/test3.jfif
  Corona-tracker/views/images/test4.jfif
  Corona-tracker/views/images/vaccine.gif
  Corona-tracker/views/images/vaccine1.gif
  Corona-tracker/views/images/vaccine2.gif
  Corona-tracker/views/index.hbs
  Corona-tracker/views/js/hosp.js
  Corona-tracker/views/js/main.js
  Corona-tracker/views/js/test.js
  Corona-tracker/views/js/vaccination.js
  Corona-tracker/views/js/world.js
  Corona-tracker/views/motivation.hbs
  Corona-tracker/views/news.hbs
  Corona-tracker/views/partials/footer.hbs
  Corona-tracker/views/partials/header.hbs
  Corona-tracker/views/partials/js_links.hbs
  Corona-tracker/views/partials/links.hbs
  Corona-tracker/views/testing.hbs
  Corona-tracker/views/vaccination.hbs
  Corona-tracker/views/world.hbs
  Index.md
Labels: LGMSOC21, 🟥 Level4

#228 restaurant website added.
  Index.md
  Restaurant-website/index.html
  Restaurant-website/index.js
  Restaurant-website/package-lock.json
  Restaurant-website/package.json
  Restaurant-website/public/css/style.css
  Restaurant-website/public/images/about.png
  Restaurant-website/public/images/contact.png
  Restaurant-website/public/images/homepage.png
  Restaurant-website/public/images/img1.jpg
  Restaurant-website/public/images/img2.jpg
  Restaurant-website/public/images/img3.jpg
  Restaurant-website/public/images/menu.png
  Restaurant-website/readme.md
Labels: LGMSOC21, 🟥 Level4

#233 Updated readme.md
  flask_news_project/readme.md
Labels: LGMSOC21

#235 Updated readme.md of typing speed project
  Typing Speed Test Website/README.md
Labels: LGMSOC21

#234 Update readme.md of breaking bad characters
  breaking-bad-characters/README.md
Labels: LGMSOC21

#240 Speed distance time calculator
  Index.md
  speed-distance-time-calculator/CalcDistance.html
  speed-distance-time-calculator/CalcSpeed.html
  speed-distance-time-calculator/CalcTime.html
  speed-distance-time-calculator/images/distance.png
  speed-distance-time-calculator/images/distanceCal.png
  speed-distance-time-calculator/images/index.png
  speed-distance-time-calculator/images/speed.jpg
  speed-distance-time-calculator/images/speedCal.png
  speed-distance-time-calculator/images/time.jpg
  speed-distance-time-calculator/images/timeCal.png
  speed-distance-time-calculator/index.html
  speed-distance-time-calculator/readme.md
  speed-distance-time-calculator/style.css
Labels: LGMSOC21

#227 Patch
  Index.md
  todolist/.gitignore
  todolist/Readme.md
  todolist/app.js
  todolist/date.js
  todolist/images/main.PNG
  todolist/images/work.PNG
  todolist/index.html
  todolist/package-lock.json
  todolist/package.json
  todolist/public/css/styles.css
  todolist/views/footer.ejs
  todolist/views/header.ejs
  todolist/views/list.ejs
Labels: LGMSOC21, 🟥 Level4

#245 Created LICENSE
  LICENSE
Labels: LGMSOC21, 🟪 Level0

#242 Simple calculator using flask
  Index.md
  Simple Calculator (Flask)/README.md
  Simple Calculator (Flask)/app.py
  Simple Calculator (Flask)/static/style.css
  Simple Calculator (Flask)/templates/index.html
Labels: LGMSOC21

#243 Adding the photo--editor folder in the repo
  Index.md
  photo -- editor/README.md
  photo -- editor/WhatsApp Image 2021-07-17 at 23.15.55 (1).jpeg
  photo -- editor/image (2) (1).png
  photo -- editor/image (3).png
  photo -- editor/image-editor.css
  photo -- editor/index.html
  photo -- editor/index.php
  photo -- editor/script.js
  photo -- editor/style.css
Labels: LGMSOC21, 🟥 Level4

#232 Temperature Convertor added
  Index.md
  Temperature Convertor/README.md
  Temperature Convertor/assets/cel-far.png
  Temperature Convertor/assets/home.png
  Temperature Convertor/assets/same-units.jpg
  Temperature Convertor/index.html
  Temperature Convertor/script.js
  Temperature Convertor/style.css
Labels: LGMSOC21, 🟥 Level4

#246 added some badges to the README
  README.md
Labels: LGMSOC21, 🟪 Level0

#237 #140 band website
  Band Website/Readme.md
  Band Website/images/Paris.jpg
  Band Website/images/background.jpg
  Band Website/images/band.png
  Band Website/images/contact.png
  Band Website/images/homepage.png
  Band Website/images/hoverEffect.png
  Band Website/images/map.jpg
  Band Website/images/member.jpg
  Band Website/images/modal.png
  Band Website/images/newYork.jpg
  Band Website/images/sanFransisco.jpg
  Band Website/images/tourDates.png
  Band Website/index.html
  Band Website/script.js
  Band Website/style.css
  DiceGame/Readme.md
  Index.md
Labels: LGMSOC21, 🟥 Level4

#249 Add randommealgenerator
  Index.md
  Random Meal-generator/README.md
  Random Meal-generator/index.html
  Random Meal-generator/script.js
  Random Meal-generator/style.css
Labels: LGMSOC21

#255 Added image in the readme of rock paper scissor game
  Rock-Paper-Scissor Game/README.md
Labels: LGMSOC21, 🟪 Level0

#254 Added img in the readme of react app
  React-App/README.md
  React-App/demo.png
  React-App/package-lock.json
  React-App/package.json
Labels: LGMSOC21, 🟪 Level0

#259 updated idex.md
  Index.md
Labels: LGMSOC21, 🟪 Level0

#260 added relaxerapp
  Index.md
  Relaxer App/README.md
  Relaxer App/index.html
  Relaxer App/script.js
  Relaxer App/style.css
Labels: LGMSOC21, 🟥 Level4

#121 Added Payment gateway integration
  payment_integration/README.md
  payment_integration/detail.css
  payment_integration/details.html
  payment_integration/index.html
  payment_integration/payment.js
  payment_integration/style.css
Labels: LGMSOC21, under-review, 🟥 Level4

#272 Sudoku Solver
  Index.md
  Sudoku Solver/README.md
  Sudoku Solver/WhatsApp Image 2021-07-21 at 22.41.36 (1).jpeg
  Sudoku Solver/index.html
  Sudoku Solver/script.js
  Sudoku Solver/style.css
Labels: LGMSOC21, 🟥 Level4

#276 Duplicates removed from Index.md
  Index.md
Labels: LGMSOC21, 🟪 Level0

#279 Counter app
  Corona-tracker/package-lock.json
  Counter_App/.gitignore
  Counter_App/README.md
  Counter_App/counterApp.png
  Counter_App/package-lock.json
  Counter_App/package.json
  Counter_App/public/favicon.ico
  Counter_App/public/index.html
  Counter_App/public/logo192.png
  Counter_App/public/logo512.png
  Counter_App/public/manifest.json
  Counter_App/public/robots.txt
  Counter_App/src/.gitignore
  Counter_App/src/App.js
  Counter_App/src/README.md
  Counter_App/src/counterApp.png
  Counter_App/src/index.js
  Counter_App/src/package-lock.json
  Counter_App/src/package.json
  Counter_App/src/style.css
  Index.md
Labels: LGMSOC21, 🟥 Level4

#282 Added bmi calculator using js
  BMI Calculator (JS)/index.html
  BMI Calculator (JS)/readme.md
  BMI Calculator (JS)/script.js
  BMI Calculator (JS)/style.css
  Index.md
Labels: LGMSOC21, 🟥 Level4

#290 Corrected drumkit(dark mode) readme images
  DRUM(darkmode)/README.md
Labels: LGMSOC21

#287 Maths quiz game
  Index.md
  Maths quiz game/README.md
  Maths quiz game/quiz.css
  Maths quiz game/quiz.html
Labels: LGMSOC21

#291 Personal blog
  Index.md
  Personal-Blog/images/fashion.jpg
  Personal-Blog/images/mobile1.png
  Personal-Blog/images/mobile2.png
  Personal-Blog/images/mobile3.png
  Personal-Blog/images/page1.png
  Personal-Blog/images/page2.png
  Personal-Blog/images/page3.png
  Personal-Blog/images/woods.jpg
  Personal-Blog/index.html
  Personal-Blog/mobile.css
  Personal-Blog/readme.md
  Personal-Blog/style.css
Labels: LGMSOC21

#303 Readme file improvement of movie-website project
  Movie-Website/README.md
Labels: LGMSOC21, 🟩 Level1

#299 food website added.
  Food-Website/bg1.jpg
  Food-Website/debug.log
  Food-Website/images/main.png
  Food-Website/images/mobiles1.png
  Food-Website/images/mobiles2.png
  Food-Website/index.html
  Food-Website/logo.jpg
  Food-Website/notification-image.jpg
  Food-Website/readme.md
  Food-Website/style.css
  Index.md
Labels: LGMSOC21, 🟥 Level4

#293 darkmode_todolist
  Index.md
  darkmode_todolist/.gitignore
  darkmode_todolist/Readme.md
  darkmode_todolist/app.js
  darkmode_todolist/date.js
  darkmode_todolist/images/main.PNG
  darkmode_todolist/images/work.PNG
  darkmode_todolist/index.html
  darkmode_todolist/package-lock.json
  darkmode_todolist/package.json
  darkmode_todolist/public/css/styles.css
  darkmode_todolist/views/footer.ejs
  darkmode_todolist/views/header.ejs
  darkmode_todolist/views/list.ejs
Labels: LGMSOC21, 🟥 Level4

#308 Added Classifiers using JS
  Classifier-Using-JS/Classifiers/classifier.css
  Classifier-Using-JS/Classifiers/languageAnalysis.html
  Classifier-Using-JS/Classifiers/newsAnalysis.html
  Classifier-Using-JS/Classifiers/script.js
  Classifier-Using-JS/Classifiers/textAnalysis.html
  Classifier-Using-JS/README.md
  Classifier-Using-JS/demo.gif
  Classifier-Using-JS/index.html
  Classifier-Using-JS/style.css
  Index.md
Labels: LGMSOC21, 🟥 Level4

#314 JavaScript Game readme updated
  JAVASCRIPT GAME/README.md
Labels: LGMSOC21, 🟩 Level1
